### ISSUE TITLE
import error- no module named GTK

### ISSUE THREAD

**Issue by blurymind** [labyrinth-team/labyrinth#15]
I get this error message:

[fox@darkstar ~]$ labyrinth 
Traceback (most recent call last):
  File "/usr/bin/labyrinth", line 25, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/labyrinth_lib/__init__.py", line 4, in main
    from .launch import main
  File "/usr/lib/python3.4/site-packages/labyrinth_lib/launch.py", line 10, in <module>
    import gtk
ImportError: No module named 'gtk'

**Comment by blurymind** [comment]
note:
I am trying to make a PKGBUILD for arch linux users:
https://aur.archlinux.org/packages/labyrinth-git/

But the resulting build gives me the above error!

**Comment by blurymind** [comment]
nevermind, I renamed python to python2.7 and that fixed it

**Comment by takluyver** [comment]
I tried porting to GTK 3 so I could also port to Python 3, but I hit some problems and gave up. It may be feasible now, but for the moment, labyrinth remains Python 2 only.
