### ISSUE TITLE
ctrl-s to save mutliple times presents 'save as...' dialog each time

### ISSUE THREAD

**Issue by hughperkins** [labyrinth-team/labyrinth#17]
Nice project by the way :-)

ctrl-s to save mutliple times presents 'save as...' dialog each time.

**Comment by hughperkins** [comment]
Hmmm, you have some weird thing where you have two possible file locations:
- some location in .local
- the locaiton that yo uspecify each time you press ctrl-s

That complicates things...  and is not very standard.

I would think standard is either:
- jump straight to a new empty map, have 'load...' to load some previous map
- 'save' will save to whatever you loaded from, or pop up a 'save as...' dialog if it's new
- (maybe) have a 'recent files' list

Standard is usually good, unless you have a relaly good reason for breaking with standard :-)

**Comment by takluyver** [comment]
Hi Hugh - the idea with this is that maps are automatically saved to a hidden location, so the user needn't worry about locating them on their filesystem. So when you hit Ctrl-S, that's *export* rather than save. I agree that that's non-standard, but that's how Labyrinth has been for a long time.

It is also rather unmaintained at the moment - I was the latest person to work on it, but I never felt that there was much of a community around it, so I moved on to other projects. If you want to help improve it, jump right in!

**Comment by hughperkins** [comment]
Haha, our replies crossed :-D

**Comment by hughperkins** [comment]
Ok, so you're saying, you have no opinion on where the project goes?  If I strip the opening dialog box, that's ok with you?

**Comment by hughperkins** [comment]
Hmmm, seems sinhac has bee ndoing a bunch of work https://github.com/labyrinth-team/labyrinth/network

**Comment by hughperkins** [comment]
Oh my lordie, sinhac's connections look really bizarroid :-P  I shall stick with your version, and my temporary hack, for now :-)

**Comment by hughperkins** [comment]
how sinhac's connections look:
![sinhacconnections](https://cloud.githubusercontent.com/assets/123560/15275134/17e3ab50-1abb-11e6-86e0-f2dc15503728.png)

**Comment by takluyver** [comment]
I do care a bit, I'm afraid. If you strip the opening maps view, anybody who is using Labyrinth and upgrades will lose them. I think a better solution would be to change the keyboard shortcut for export to something else. See for instance Hackpad - when you hit Ctrl-S, a little notification pops up in the corner saying "No worries, it's automatically saved already". In many ways, I think this is a better paradigm than the normal 'remember to save every few seconds!' design of desktop apps, so I would be disappointed if Labyrinth was stripped back to the 'standard' interface.

**Comment by hughperkins** [comment]
Ok, I will leave you to figure out how to handle that.  My personal requirements (preferences if you prefer :-) ) are:
- can open the 'exported' file directly, skipping the internal db dialog
- save/export/whatever will then directly save to that filepath, without any additional dialog boxes

I have no preference over whether this is called 'save' or 'export' or whatever, just as long as I have some way of doing these two things :-)

**Comment by hughperkins** [comment]
(or .... eliminate the internal db, and the initial dialog is basically a 'recent files' list, but I think that's not how you want it to work, right?)

**Comment by hughperkins** [comment]
(some additional context: I sav eeverything up to github, so just saving to internal db doesnt do what I want.  my workflow looks like this:
- open doc from github repo
- work on it, ctrl-s'ing as I go
- commit to github repo, upload
)

**Comment by hughperkins** [comment]
(actually... along similar lines, it would be good if the save/export saved as plain xml, rather than tarring, way more compatible with saving in git :-)  Just my own opinion...)

**Comment by takluyver** [comment]
Maybe the answer is to support both ways of working - if you open a map from the internal list, it would autosave and have an export option in the menu (as it already does), but if you open a map from an exported file, it would have standard 'save' and 'save as' menu entries.

**Comment by hughperkins** [comment]
Yes, sounds reasonable :-)

**Comment by hughperkins** [comment]
As you can see, I've made my own fork which skips the innitial Browser window, opening a new map if no filepath given, else opens the filepath given.  All is in xml, no tarring.

https://github.com/labyrinth-team/labyrinth/pull/20

Closing this issue, since I think I've communicated my own opinions on the subject, and now it's really just down to personal preferences :-)
