### ISSUE TITLE
can not input chinese.

### ISSUE THREAD

**Issue by levinit** [labyrinth-team/labyrinth#24]
os:archlinux
de:gnome
input:fcitx-pinyin

**Comment by takluyver** [comment]
Labyrinth is, as you spotted, a bit dead. But if you want to make a pull request, I'll try to find time to look at it merge it. I've no idea about chinese input, though, so I don't know what it needs.

**Comment by baimafeima** [comment]
@levinit Do you know how to get it to work with Chinese?

**Comment by levinit** [comment]
@baimafeima  复制+粘贴 :）

**Comment by levinit** [comment]
@baimafeima 另一款工具叫 vym也不错

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Ramos M7 发送_
